### ISSUE TITLE
adding hover effect at top icons

### ISSUE THREAD

**Issue by solanki505** [DSC-JSS-NOIDA/HackHive#1]
![Screenshot 2024-05-09 004106](https://github.com/DSC-JSS-NOIDA/HackHive/assets/158484284/41a6a779-bb17-4abc-8529-62b9cb2886d0)

I want to work on this issue, please assign me this to improve the features of the site. 

I would like to work on this issue please assign me this under GSSOC'24.

**Comment by CharanAdithya6505** [comment]
I want to work on this issue, pls assign i will add hover effect and some more effects to ui

**Comment by AbhinaySngh** [comment]
hey please assign me this issue, i assure you will be happy with my work(GSSOC'24).
