### ISSUE TITLE
font family is not looking great

### ISSUE THREAD

**Issue by venkatasai24** [DSC-JSS-NOIDA/HackHive#10]
As I found this issue and I'm a GSSOC'24 contributor, pls assign this to me @hereisSwapnil

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by hereisSwapnil** [comment]
@venkatasai24 Please make sure the font family matches the Figma Design

**Comment by venkatasai24** [comment]
Are you assigning it to me? @hereisSwapnil

**Comment by RamitVishwakarma** [comment]
@venkatasai24  I have assigned the issue to you make sure you get the font from the figma design add it in tailwind

**Comment by venkatasai24** [comment]
> 

Hey @RamitVishwakarma, on the website, you have already used the mentioned font family(```Nunito-Sans```).
But ```sans-serif``` is looking much great.
Here are the results
![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/103911586/3c930c1e-e168-4026-b482-e73de078c7b4)
![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/103911586/fcb020be-9032-4e28-908b-7f8810689b86)
Do you want me to continue with ```sans-serif``` ??

**Comment by RamitVishwakarma** [comment]
The issue with this is that the fonts are not actually applied currently in the code so if you fix it create a pr 
And no i would like the fonts to be same as the design

**Comment by venkatasai24** [comment]
> The issue with this is that the fonts are not actually applied currently in the code so if you fix it create a pr And no i would like the fonts to be same as the design

Fine !!
