### ISSUE TITLE
[Bug]: HomePage not responsive

### ISSUE THREAD

**Issue by aryansharma220** [DSC-JSS-NOIDA/HackHive#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

HomePage is not responsive.

### Add ScreenShots

![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/133234867/38f13364-679c-47d3-a63e-af8c7283c94c)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by RamitVishwakarma** [comment]
@aryansharma220  someone is already working on fixing the dark mode for homepage so there may be conflicts I ll assign you the issue as of now but you might have to fix conflicts later on

**Comment by aryansharma220** [comment]
ok @RamitVishwakarma will take care of it
