### ISSUE TITLE
[Feature Request]: Styling Articles of Blog Page in Light and Dark Mode

### ISSUE THREAD

**Issue by DurgaPrasad-R** [DSC-JSS-NOIDA/HackHive#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This is regarding an improvement of the styling of the articles present in the blog page. The articles look same in both dark and light modes. I would like to make them look attractive on toggling between dark and light modes. It involves alignment of Article card and proper structuring of the articles and their corresponding content.

### Use Case

This improves the user interface when the user navigates to the blog page.

### Benefits

**Before adding styles:**
**Light Mode:**
![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/111352968/4c8a7212-ecbd-4906-871d-ec5131abfa0b)
**Dark Mode:**
![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/111352968/5fc3ede3-3fd2-4fb6-a6d6-10f234973ce3)
**After adding the styles:**
**Light Mode:**
![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/111352968/c37eb6b8-ae6e-4fa0-bd8f-0d475f9465e0)
**Dark Mode:**
![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/111352968/553ae893-ce68-43b6-809d-16c225f2f0d7)

### Priority

High

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DurgaPrasad-R** [comment]
Hello @RamitVishwakarma, I'm new to GSSoC can I close this issue now? or Should I do anything?

**Comment by RamitVishwakarma** [comment]
@DurgaPrasad-R  sure you can start working on this I have assigned you this
No need to close the issue until you have created a pr and I have merged it

**Comment by DurgaPrasad-R** [comment]
#118 I have created a PR and I just got to know that you've merged it.

**Comment by RamitVishwakarma** [comment]
@DurgaPrasad-R  hehe okay
