### ISSUE TITLE
Adding cards for hackathons.

### ISSUE THREAD

**Issue by yashi-15** [DSC-JSS-NOIDA/HackHive#3]
- The hackathons list would look better with each hackathon inside a card. 

- Each card would be of appropriate styling according to the overall website design and color scheme, along with subtle hover effects to increase user engagement.

Kindly assign this issue to me under GSSoC'24.

**Comment by AbhinaySngh** [comment]
hey could you please assign this issue to me, i assure you will be happy with my work?

**Comment by RamitVishwakarma** [comment]
Assigned the issue to both of you but before starting work on this make sure to look at the design file
https://www.figma.com/design/9HzyqaEl4SXVY4iZIA0SFp/HackHive

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by TomLucasakaTGeek** [comment]
I would like to work on this issue, please assign it to me.
