### ISSUE TITLE
Migrate Normal Css to Tailwind classes

### ISSUE THREAD

**Issue by RamitVishwakarma** [DSC-JSS-NOIDA/HackHive#5]
The project needs to be written in tailwind classes so all the CSS needs to be converted into Tailwind classes

**Comment by Prithwi32** [comment]
@RamitVishwakarma Please could you assign me this issue under GSSoC'24

**Comment by RamitVishwakarma** [comment]
@Prithwi32 done

**Comment by Prithwi32** [comment]
> @Prithwi32 done

Thank you

**Comment by OmChillure** [comment]
@RamitVishwakarma Can you please assign this issue to me under GSSoc'24!

**Comment by Debanjannnn** [comment]
Dear @RamitVishwakarma , please assign me the task related to the code conversion to Tailwind CSS , I  have fixed the  navbar, landing page, and login page on my local system.

**Comment by Athul28** [comment]
@RamitVishwakarma please assign me this task

**Comment by Prithwi32** [comment]
@RamitVishwakarma Please could you check out PR
