### ISSUE TITLE
add hover on different links and buttons.

### ISSUE THREAD

**Issue by dev04sa** [DSC-JSS-NOIDA/HackHive#56]
as you can see , there is no hover effect and transition present on buttons .
i want to add that one , kindly assign this issue to me.

https://github.com/DSC-JSS-NOIDA/HackHive/assets/129666293/8b78c80a-b776-4b16-8655-9ac3ed275d95

**Comment by SandipGyawali** [comment]
@dev04sa is it open to solve if yes can you assign me ?

**Comment by RamitVishwakarma** [comment]
@dev04sa  its already been done
