### ISSUE TITLE
[feature]Infinity Carousel with company names

### ISSUE THREAD

**Issue by AshishKumarSamantaray** [DSC-JSS-NOIDA/HackHive#57]
Infinity carousels with company names would look better to this website. Please assign me and i can do the same for you.
![Virtuo Learn - Brave 5_12_2024 4_19_28 PM](https://github.com/DSC-JSS-NOIDA/HackHive/assets/121350516/8a98ee3c-35d0-48df-84cb-dd7e5b49958c)

**Comment by RamitVishwakarma** [comment]
@AshishKumarSamantaray  that is not required as of now
