### ISSUE TITLE
Footer Design and Fixing broken link to Hackathon Page

### ISSUE THREAD

**Issue by Prithwi32** [DSC-JSS-NOIDA/HackHive#6]
Key points achieved:
*Footer design according to Figma design
*Fixing bug of hackathon page link

**Comment by Prithwi32** [comment]
@RamitVishwakarma Please could you assign me this issue under GSSoC'24

**Comment by OmChillure** [comment]
@RamitVishwakarma Can you Please assign this issue to me under GSSoC'24.

**Comment by Prithwi32** [comment]
@RamitVishwakarma Made PR could you check once
