### ISSUE TITLE
[Fix]: Unnecessary removed css files import

### ISSUE THREAD

**Issue by AvdhutPailwan** [DSC-JSS-NOIDA/HackHive#60]
### Issue Description
The css files which were usless and were deleted still have their import statements into the files.
###Problem: it produces error during development.

### Solution:
The solution to this issue is very trivial, as it just requires the import statements of the unnecessary files to be removed.

### Screenshots:
![Screenshot from 2024-05-12 16-19-55](https://github.com/DSC-JSS-NOIDA/HackHive/assets/74597375/358966b1-6d3f-481e-9489-c451f27d39cd)

Please assign this issue to me under GSsoc24.
@RamitVishwakarma

**Comment by RamitVishwakarma** [comment]
Alright go ahead on this

**Comment by AvdhutPailwan** [comment]
@RamitVishwakarma please check the changes which are made and please give feedback if there is any as I am new to open source I would really appreciate some words of guidance from you and I am looking forward to work on more complex issues moving forward.

**Comment by AvdhutPailwan** [comment]
This issue was fixed on the latest commit : #37.
