### ISSUE TITLE
Improving organisations.css making it dynamically sliding

### ISSUE THREAD

**Issue by Amruta7203** [DSC-JSS-NOIDA/HackHive#61]
Enhancing organisations.css file by adding padding and dynamic effects.

**Comment by Amruta7203** [comment]
I would like to work on this issue under GSSOC'24. Request you to assign this task to me.

**Comment by RamitVishwakarma** [comment]
@Amruta7203 we are not planning on using normal css We are using Tailwind classes  for styling also that section is already been updated
