### ISSUE TITLE
Commit hooks for linting

### ISSUE THREAD

**Issue by AvdhutPailwan** [DSC-JSS-NOIDA/HackHive#69]
@RamitVishwakarma Sir as you mentioned in the issue #51 you want a consistent formatting for the code styling with prettier. It can be implemented with pre-commit hooks. I would like to add pre-commit hooks to the project for linting. 

Please assign me this issue under gssoc

**Comment by RamitVishwakarma** [comment]
@AvdhutPailwan sure you can work on it

**Comment by AvdhutPailwan** [comment]
@RamitVishwakarma Are there any changes or updates needed? 

since we have made changes and added husky one more step is required now to set up the project for which I have opened a ticket #74 to update the documentation please review it and suggest if any more changes are required and please do assign me ticket #74 under gssoc
