### ISSUE TITLE
Blog page design

### ISSUE THREAD

**Issue by Prithwi32** [DSC-JSS-NOIDA/HackHive#7]
*Adding Blog page for website

**Comment by Prithwi32** [comment]
@RamitVishwakarma Please could you assign me this issue under GSSoC'24

**Comment by sahithi000** [comment]
Can u please assign me this issue under GSSOC24

**Comment by TomLucasakaTGeek** [comment]
Can you assign this issue to me, please.

**Comment by Dev-AyushTrivedi** [comment]
i can create interactive and eye catching website could you please assign it to me..

**Comment by Prithwi32** [comment]
@RamitVishwakarma check out PR
