### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [DSC-JSS-NOIDA/HackHive#70]
Currently, there is no issue template for this repo, so I want to add it which will look like this 👇

![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/73957207/f636a008-27e4-4957-b389-413187146a0f)

- **Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.**
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/DSC-JSS-NOIDA/HackHive/assets/73957207/73f75614-9b72-4719-b82d-6c870431bae2)

**Comment by TonyStark-47** [comment]
And I want to work on this issue. So, kindly assign this issue to me under GSSOC'24.

**Comment by RamitVishwakarma** [comment]
@TonyStark-47  done

**Comment by TonyStark-47** [comment]
Hey @RamitVishwakarma, I raised a PR related to this issue. Check it out.
