### ISSUE TITLE
Docs: Project setup instructions in README.md

### ISSUE THREAD

**Issue by AvdhutPailwan** [DSC-JSS-NOIDA/HackHive#74]
### Issue:
Current README.md file has instructions on cloning and committing to the project but it has no instructions for setting up the project which may cause problem for the newcomers who wish to contribute to the project. 

@RamitVishwakarma I would like to contribute to the documentation under gssoc.

**Comment by Suruchibharti** [comment]
hey  ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.
