### ISSUE TITLE
[Bug]: Social media icons are not visible and not working

### ISSUE THREAD

**Issue by shikharg1110** [DSC-JSS-NOIDA/HackHive#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Social media icons are not visible and not working

### Add ScreenShots

![gssoc](https://github.com/DSC-JSS-NOIDA/HackHive/assets/114243045/f67dc6dd-bfb4-41f3-ada0-dae2871444ae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shikharg1110** [comment]
Kindly assign this issue to me under gssoc. I would really like to contribute

**Comment by AvdhutPailwan** [comment]
@shikharg1110 please pull the latest changes of the repo and run the project locally before posting it as an issue. This has been already addressed by someone.

**Comment by RamitVishwakarma** [comment]
Already fixed please pull the changes
