### ISSUE TITLE
[Bug]: The social media icons do not come up with their respective image

### ISSUE THREAD

**Issue by pruthviraj-desale** [DSC-JSS-NOIDA/HackHive#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At the bottom of the page, the social media icons don not appear with their respective image and only refresh the page upon clicking, would like to link them with their respective pages and put the linked images to them

### Add ScreenShots

![image_2024-05-14_154952416](https://github.com/DSC-JSS-NOIDA/HackHive/assets/132280572/5c03fa53-a8cc-42ca-bf1d-e5d8ea350db0)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by pruthviraj-desale** [comment]
@RamitVishwakarma please assign this issue to me under GSSoC

**Comment by RamitVishwakarma** [comment]
@pruthviraj-desale sure you can work on this i ll assign it to you make sure to refer the figma designs

**Comment by pruthviraj-desale** [comment]
pr merged issue closed
